name: Clojure CI

on:
  push:
    branches: [ "1.20.2" ]
  pull_request:
    branches: [ "1.20.2" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
